name: shell commads

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multi line script
        run: |
          node -v
          npm -v

      - name: python run-shell-command
        run: |
          print("Hello python")
        shell: python

  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory powershell
        run: Get-Location
      - name: Bash
        run: pwd
        shell: bash
